<?php global $mySession; ?>

<script>
document.getElementById('myButton').onclick = function() {
    document.getElementById('btnsub').removeAttribute('readonly');
};

$(document).ready(function() {
          $('btnsub').addAttribute('readonly');
        });
</script>
                <div class="page-content-wrap">
                
                    <div class="row">
                        <div class="col-md-12">
                            
			<form class="form-horizontal" enctype="multipart/form-data" method="post">

                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"><strong>आरती का विवरण</strong></h3>
                                    <ul class="panel-controls">
                                        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                                    </ul>
                                </div>
                                
                                <div class="panel-body">  
                                	<div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">आरती का फोटो</label>
                                        <div class="col-md-6 col-xs-12">                                      
										<? echo $this->myform->Aarti_Pic?>    

<!--<input type="file" class="fileinput btn-primary" name="filename" id="filename" title="Browse file"/>-->
                                            <span class="help-block">Input type file</span>
                                        </div>
                                    </div>                                                                      
                                    
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">आरती का नाम</label>
                                        <div class="col-md-6 col-xs-12">                                            
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                <? echo $this->myform->Aarti_Title?>
                                            </div>                                            
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">आरती का लिंक</label>
                                        <div class="col-md-6 col-xs-12">                                            
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                <? echo $this->myform->Aarti_Audio_Link?>
                                            </div>                                            
                                        </div>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Active</label>
                                        <div class="col-md-6 col-xs-12">                                            
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                <? echo $this->myform->Active?>
                                            </div>                                            
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">आरती का विवरण</label>
                                        <div class="col-md-6 col-xs-12">                                            
                                            <div class="input-group">
                                                <span class="input-group-addon" style="vertical-align:top"><span class="fa fa-pencil"></span></span>
                                                <? echo $this->myform->Aarti_Dtl?>
                                            </div>                                            
                                        </div>
                                    </div>
                                    
                                    
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">आरती की ऑडियो फाइल</label>
                                        <div class="col-md-6 col-xs-12">                                      
										<? echo $this->myform->Aarti_Audio?>    

<!--<input type="file" class="fileinput btn-primary" name="filename" id="filename" title="Browse file"/>-->
                                            <span class="help-block">Input type file</span>
                                        </div>
                                    </div>
                                   
                                  <div class="panel-footer">
                                    <input type="submit" class="btn btn-primary " value="Submit" id="btnsub"/>
<button type="button" onclick="Javascript:window.location.href='<?=BASE_PATH?>artical/index';" class="btn btn-default pull-right">Back To Temple</button> 
                                </div>  	
                                </div>
                                
                            </div>
			</form>
                            
                        </div>
                    </div>                    
                    
                </div>
                <!-- END PAGE CONTENT WRAPPER --> 