<?php global $mySession;?>

<link rel="stylesheet" type="text/css" href="<?=WEB_URL?>mp3-player/demo/360-player/360player.css" />
<script type="text/javascript" src="<?=WEB_URL?>mp3-player/demo/360-player/script/berniecode-animator.js"></script>
<script type="text/javascript" src="<?=WEB_URL?>mp3-player/script/soundmanager2.js"></script>
<script type="text/javascript" src="<?=WEB_URL?>mp3-player/demo/360-player/script/360player.js"></script>

<script type="text/javascript" language="javascript">
	$(document).ready(function() {
        $('li#art').addClass('active');
        $('li#art_ch').addClass('active');
		});	
</script>
<!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li><b>क्षत्रिय गांछा समाज, प्रधान कार्यालय सुमेरपुर (राजस्थान) || Admin Panel</b></li>
                    
                </ul>
                <!-- END BREADCRUMB -->
<div class="page-title">                    
    <h2><span class="fa fa-arrow-circle-o-left"></span> आरती की लिस्ट</h2>
</div>                
<!-- PAGE CONTENT WRAPPER -->
	<div class="page-content-wrap">                
                
                    <div class="row">
                        <div class="col-md-12">

                            <!-- START DEFAULT DATATABLE -->
                            <div class="panel panel-default">
                                <div class="panel-heading">                                
                                    
                                    <ul class="panel-controls">
<li style="width:50px;">
<a class="btn btn-success btn-rounded pull-left" href="<? echo BASE_PATH?>aarati/add">&nbsp;<i class="fa fa-plus"></i></a>
</li>
                                        <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                                        
                                        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                                    </ul>                                
                                </div>
                                <div class="panel-body">
                                    <table class="table datatable">
                                        <thead>
                                            <tr>
                                                <th>फोटो</th>
                                                <th>Mp3 ऑडियो</th>
                                                <th>आरती का नाम</th>
                                                <th>आरती का विवरण</th>
                                                <th>पोस्ट बाय </th>
                                                <th> Active</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                           <?php 
												$i=1;
												foreach($this->Aarti_Data as $res) { 
											?>
                                            <tr>
                                                <td width="100">
			<?php 
				if($res['Aarti_Pic']=='')
			{
			?>
				 <img width="80" height="80"  src="<?=UP_IMG?>no-image.jpg" >
				
			<?php }else{ ?>
			<img width="80" height="80" src="<?=UP_IMG?>Aarti_Data/thumbs/<? echo $res['Aarti_Pic']; ?>" style=""/>
			<? }?>
                                                </td>
												<td>
													<?php 
														if($res['Aarti_Pic']=='')
													{
													?>
                                                    No File Found
                                                    <?php }else{ ?>
                                                    <div style="float:left;display:inline;min-width:50px; margin-top:5px; "> 
 														<div class="ui360" style="margin-top:-0.55em">
                                                        	<a href="<?=UP_IMG?>Aarti_Data/Aarti_Audio/<?php echo $res['Aarti_Audio']; ?>"></a>
                                                        </div>
													</div>
												<? }?>
                                                </td>
                                                
                                                <td><? echo $res['Aarti_Title']; ?></td>
                                                
                                                <td><?php echo substr($res["Aarti_Dtl"],0,190).' ........'?></td>
											    <td><? echo $res['Post_By']; ?></td>
                                                <td><? echo $res['Active']; ?></td>

                                                <td>


<a class="btn btn-info btn-rounded btn-sm" href="<? echo BASE_PATH.'aarati/edit/Aarti_Id/'.$res['Aarti_Id']?>">
Edit <li class="fa fa-pencil"></li>
</a>
&nbsp;&nbsp;
<a class="btn btn-danger btn-rounded btn-sm " href="<? echo BASE_PATH.'aarati/del/Aarti_Id/'.$res['Aarti_Id']?>&amp;<?php echo $res['Artical_Img']?>" onclick="return confirm('Are you sure want to delete this record')">Del <li class="fa fa-times"></li></a>


                                                    </td>
                                            </tr>
                                           <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- END DEFAULT DATATABLE -->

                            

                        </div>
                    </div>                                
                    
                </div>
<!-- PAGE CONTENT WRAPPER -->  